apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/urls: '["https://metnmat-website-127977052991.asia-south1.run.app","https://metnmat-website-zrfgtoog2q-el.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-south1
    commit-sha: c162d725942a8cce07f8ff1eeff979d42c4470aa
    gcb-build-id: 0666cd79-f0c2-4dcd-b3b9-9b13da93ea26
    gcb-trigger-id: 36345015-17af-40ad-bf65-81970d2a4cd7
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    run.googleapis.com/satisfiesPzs: 'true'
  name: metnmat-website
  namespace: '127977052991'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 579.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: ghxnwgisrl
        commit-sha: c162d725942a8cce07f8ff1eeff979d42c4470aa
        gcb-build-id: 0666cd79-f0c2-4dcd-b3b9-9b13da93ea26
        gcb-trigger-id: 36345015-17af-40ad-bf65-81970d2a4cd7
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: QUOTE_FROM_EMAIL
          value: METNMAT <onboarding@resend.dev>
        - name: QUOTE_NOTIFY_EMAIL
          value: sales@metnmat.com
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: RAZORPAY_KEY_ID
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: RAZORPAY_KEY_SECRET
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: RESEND_API_KEY
        - name: INTERNAL_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: INTERNAL_API_KEY
        - name: OPEN_EXCHANGE_RATES_APP_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: OPEN_EXCHANGE_RATES_APP_ID
        - name: UPSTASH_REDIS_REST_URL
          value: https://advanced-zebra-41141.upstash.io
        - name: RAZORPAY_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: RAZORPAY_WEBHOOK_SECRET
        - name: UPSTASH_REDIS_REST_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: UPSTASH_REDIS_REST_TOKEN
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: latest
              name: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: GOOGLE_CLIENT_SECRET
        - name: CMS_OAUTH_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: CMS_OAUTH_KEY
        - name: ANALYTICS_GEO_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: analytics-geo-token
        image: asia-south1-docker.pkg.dev/metnmat-website/cloud-run-source-deploy/metnmat-website/metnmat-website:c162d725942a8cce07f8ff1eeff979d42c4470aa
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: payload-storage-sa@metnmat-website.iam.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
