// Flat ESLint config. Next.js 16 removed the `next lint` command, so the CMS
// now runs ESLint directly (see the "lint" script) with the same two Next
// presets the old .eslintrc.json extended.
import { defineConfig } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by `payload generate:importmap`; never hand-edited.
      "src/app/(payload)/admin/importMap.js",
      "scripts/_img_tmp/**",
      // One-off operator scripts, CommonJS by design; `next lint` never linted them.
      "*.cjs",
    ],
  },
  {
    // Custom Payload admin components. Their anchors target Payload's own
    // catch-all admin router (/admin/[[...segments]]), not Next pages, so the
    // Next-pages link rule is a false positive here — the website config turns
    // it off for the same reason.
    files: ["src/admin/**/*.{ts,tsx}"],
    rules: { "@next/next/no-html-link-for-pages": "off" },
  },
]);
